name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐞 Bug Fixes'
    labels:
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
