[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 180
include = '\.pyi?$'

[tool.setuptools_scm]
write_to = "src/dhapi/_version.py"
